"""tables created

Revision ID: c73e8d4eff97
Revises: 
Create Date: 2025-01-22 22:16:45.373569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73e8d4eff97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisors',
    sa.Column('AdvisorID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FullName', sa.String(length=50), nullable=False),
    sa.Column('Title', sa.String(length=70), nullable=True),
    sa.Column('Department', sa.String(length=70), nullable=False),
    sa.Column('Email', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('AdvisorID')
    )
    op.create_table('courses',
    sa.Column('CourseID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CourseCode', sa.String(length=50), nullable=False),
    sa.Column('courseName', sa.String(length=50), nullable=False),
    sa.Column('IsMandatory', sa.Boolean(), nullable=False),
    sa.Column('Credit', sa.Integer(), nullable=False),
    sa.Column('Department', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('CourseID')
    )
    op.create_table('students',
    sa.Column('StudentID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FirstName', sa.String(length=40), nullable=False),
    sa.Column('LastName', sa.String(length=40), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=False),
    sa.Column('AdvisorID', sa.Integer(), nullable=False),
    sa.Column('EnrollmentDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['AdvisorID'], ['advisors.AdvisorID'], ),
    sa.PrimaryKeyConstraint('StudentID')
    )
    op.create_table('user_advisor',
    sa.Column('UserID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Username', sa.String(length=40), nullable=False),
    sa.Column('PasswordHash', sa.String(length=40), nullable=False),
    sa.Column('RelatedID', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['RelatedID'], ['advisors.AdvisorID'], ),
    sa.PrimaryKeyConstraint('UserID')
    )
    op.create_table('studentcourseselections',
    sa.Column('SelectionID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('StudentID', sa.Integer(), nullable=False),
    sa.Column('CourseID', sa.Integer(), nullable=False),
    sa.Column('SelectionDate', sa.DateTime(), nullable=False),
    sa.Column('IsApproved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['CourseID'], ['courses.CourseID'], ),
    sa.ForeignKeyConstraint(['StudentID'], ['students.StudentID'], ),
    sa.PrimaryKeyConstraint('SelectionID')
    )
    op.create_table('transcripts',
    sa.Column('TranscriptID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('StudentID', sa.Integer(), nullable=False),
    sa.Column('CourseID', sa.Integer(), nullable=False),
    sa.Column('Grade', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['CourseID'], ['courses.CourseID'], ),
    sa.ForeignKeyConstraint(['StudentID'], ['students.StudentID'], ),
    sa.PrimaryKeyConstraint('TranscriptID')
    )
    op.create_table('user_student',
    sa.Column('UserID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Username', sa.String(length=40), nullable=False),
    sa.Column('PasswordHash', sa.String(length=40), nullable=False),
    sa.Column('RelatedID', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['RelatedID'], ['students.StudentID'], ),
    sa.PrimaryKeyConstraint('UserID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_student')
    op.drop_table('transcripts')
    op.drop_table('studentcourseselections')
    op.drop_table('user_advisor')
    op.drop_table('students')
    op.drop_table('courses')
    op.drop_table('advisors')
    # ### end Alembic commands ###
