"""password len has been 120

Revision ID: b51678746608
Revises: c73e8d4eff97
Create Date: 2025-01-25 23:47:52.069412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b51678746608'
down_revision = 'c73e8d4eff97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studentcourseselections', schema=None) as batch_op:
        batch_op.alter_column('SelectionDate',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('user_advisor', schema=None) as batch_op:
        batch_op.alter_column('PasswordHash',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('CreatedAt',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('user_student', schema=None) as batch_op:
        batch_op.alter_column('PasswordHash',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('CreatedAt',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_student', schema=None) as batch_op:
        batch_op.alter_column('CreatedAt',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('PasswordHash',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=40),
               existing_nullable=False)

    with op.batch_alter_table('user_advisor', schema=None) as batch_op:
        batch_op.alter_column('CreatedAt',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('PasswordHash',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=40),
               existing_nullable=False)

    with op.batch_alter_table('studentcourseselections', schema=None) as batch_op:
        batch_op.alter_column('SelectionDate',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###
